name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - name: Check if built docker image runs as expected
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build . --file szpp-judge-frontend.dockerfile --tag node-lib-copy-test:latest
        echo "::debug::$(docker image ls)"
        docker run --rm -- node-lib-copy-test:latest -c 'node -v && node -e "console.log(\"hello world\")" && corepack -v'
